\label{chap:conclusiones}
\subsection{Conclusiones}

Ante uno de los principales problemas en el análisis de series de tiempo mediante modelos ARIMA, como lo es la subjetividad del observador en la identificación de procesos, esta investigación ha tenido como objetivo principal siempre proponer un aporte metodológico para la selección de modelos ARIMA y por ende, una mejora en los pronósticos obtenidos a partir de estos modelos.

Las bases de este estudio se presentaron en el segundo capítulo, donde además de describir qué es una serie cronológica se explican los componentes de la misma: tendencia-ciclo, componente estacional y componente irregular. Además, se plantearon los supuestos asociados al análisis de series cronológicas, así como los distintos criterios para la identificación del modelo que gobierna a una determinada serie cronológica. Entre las distintas clases de modelos, el interés de esta investigación se centra en los modelos autorregresivos integrados de medias móviles, razón por la cual se deja claro el fundamento teórico de la ecuación de Wold y la metodología de Box-Jenkins para poder estimar los modelos autorregresivos y los modelos de medias móviles, y de esta manera justificar la unión de ambas clases en los modelos autorregresivos integrados de medias móviles. Aunado a esto, se discutió el uso de los autocorrelogramas como método de identificación de modelos para así introducir los elementos básicos del análisis combinatorio y su uso conjunto con la sobreparametrización para encontrar modelos ARIMA adecuados.

A partir de lo anterior, se describieron los materiales a usar: series cronológicas simuladas y reales (tasa de mortalidad infantil interanual, tasa de mortalidad por causa externa, incentivos salariales del sector público e intereses y comisiones del sector público). Con estos insumos, el proceso de análisis consistió en realizar un análisis exploratorio de cada serie cronológica, aplicarle a las mismas una partición de datos para dividirla en dos conjuntos de datos, entrenamiento y validación, una para ajustar los modelos y otra para evaluar la calidad de los pronósticos, respectivamente. Se realiza el ajuste de los modelos con las series simuladas y luego con las reales para posteriormente hacer un análisis de los residuales de cada modelo y verificar el cumplimiento de los supuestos discutidos previamente. Una vez estimados los modelos, se realizaron los pronósticos de todas las series cronológicas para obtener un análisis visual del comportamiento de los valores ajustados y de los pronósticos, además de evaluar la calidad de estos mediante distintas medidas de bondad de ajuste y de rendimiento.

Al aplicar la función `auto.arima()` y la sobreparametrización sobre una serie cronológica generada a partir de un $ARIMA(1,0,0)$, los modelos estimados son un $ARIMA(2,1,1)$ y un $ARIMA(1,0,0)$, respectivamente. Los errores estándar son menores al utilizar la sobreparametrización y también tiene una menor variabilidad. Las medidas de bondad de ajuste en el conjunto de datos de entrenamiento, como se muestra en el cuadro \ref{tab:comparaciones_arima_peores}, son menores en el modelo sugerido por la sobreparametrización, mientras que las mejores medidas de rendimiento las muestra el `auto.arima()`, aunque las diferencias son son muy grandes.


Al generar datos a partir de un $ARIMA(1,0,1)$ los mejores pronósticos se obtienen tanto con el `auto.arima()` como con la sobreparametrización tal y como se muestra en el cuadro \ref{tab:comparaciones_arima_peores}, pues ambos son superiores a los obtenidos mediante un $ARIMA(1,1,1)$., sin embargo, el comportamiento en la predicción es casi constante. En este escenario, los errores estándar tienen prácticamente el mismo comportamiento, tanto para la sobreparametrización como para el `auto.arima()` y el ARIMA estándar.

Al ir incorporando términos en las series no estacionales, como es el caso de los datos simulados a partir de un $ARIMA(2,0,3)$, los mejores pronósticos se obtienen mediante el uso de la sobreparametrización (ver cuadro \ref{tab:comparaciones_arima_peores}), pues la magnitud de sus errores son siempre menores, sin embargo, el comportamiento de los pronósticos también se vuelve constante, tal y como se aprecia en la Figura \ref{fig:pronostico_arima203}. Con los tres métodos utilizados, a pesar de que los pronósticos en series de orden bajo no son los mejores, entre las tres opciones la sobreparametrización brinda mejores resultados en términos de rendimiento y bondad de ajuste.

Los últimos modelos generados a partir de los datos simulados se obtuvieron de la serie cronológica proveniente de un proceso $ARIMA(4,0,2)$. Como muestra la Figura \ref{fig:pronostico_arima402}, los pronósticos son bastante competentes en los primeros periodos, pero posteriormente se van acotando; mientras que los errores estándar son prácticamente los mismos con los modelos. Las medidas de rendimiento para estas estimaciones están bastante cercanas entre sí, siendo las del `auto.arima()` ligeramente mejores. 

Cuando se consideran series cronológicas estacionales, se presenta un comportamiento similar a lo previamente descrito. Al tener una baja cantidad de parámetros en los datos simulados de un proceso estacional $ARIMA(0,0,1)(0,1,1)_{12}$, la sobreparametrización iguala los resultados obtenidos mediante la función `auto.arima()` tal y como puede apreciarse en la Figura \ref{fig:pronostico_arima001_011} y el cuadro \ref{tab:comparaciones_arima_mejores}; por lo que los errores estándar también poseen el mismo comportamiento, igualando así los intervalos de confianza.

Al incorporar más parámetros al modelo generador de los datos como en el caso del $ARIMA(2,1,4)(3,0,3)_{12}$, el cuadro \ref{tab:comparaciones_arima_mejores} y en la Figura \ref{fig:pronostico_arima214_303} muestran como la sobreparametrización logra captar de mejor manera el comportamiento de los datos, obteniendo así menores mediciones del error, es decir, los pronósticos se acercan más a los datos reales. Los errores estándar son de mayor magnitud en la sobreparametrización, lo cuál genera intervalos de confianza más amplios.

En el caso de las series de tiempo generadas a partir de datos reales, y en el caso particular de la Tasa de mortalidad infantil interanual, la función `auto.arima()` sugiere como mejor modelo un $ARIMA(2,1,0)(0,0,1)$, mientras que utilizando la sobreparametrización se tiene como mejor modelo un $ARIMA(4,1,0)(4,1,0)$. El cuadro \ref{tab:comparaciones_arima_mejores_reales} y la Figura \ref{fig:pronostico_TMII} muestran como el uso de la sobreparametrización ajusta los valores pronosticados de una mejor manera a los datos reales con respecto a utilizar `auto.arima()` o un modelo $ARIMA$ estándar. El valor mediano de los errores estándar es inferior al utilizar la sobreparametrización, lo cuál generará intervalos de confianza más acotados. Esto es de particular interés porque al tener intervalos de un mismo nivel de confianza pero más acotados, puede tenerse más certeza del posible rango que alcanzaría esta serie de tiempo e incluso otras que presenten comportamientos similares en el sentido de su correlación natural con sus periodos previos.

De manera similar, tras ajustar un modelo utilizando la función `auto.arima()` a la tasa de mortalidad por causa externa el mejor modelo sugerido es un $ARIMA(1,1,1)$, mientras que la sobreparametrización propone como mejor modelo un $ARIMA(2,0,1)(0,1,1)_{12}$. Los resultados de la Figura \ref{fig:pronostico_EXTERNA} y el cuadro \ref{tab:comparaciones_arima_peores_reales} muestran que la sobreparametrización supera a los resultados del $ARIMA$ estándar, y este a su vez supera al `auto.arima()`. Aunque no se replican a la perfección los saltos de la serie, el comportamiento general es similar, y las medidas de rendimiento y bondad de ajuste en la sobreparametrización indican que este modelo es más adecuado en comparación a los demás.

Esta información junto puede servir de insumo para construir los diferentes índices, tasas y otros indicadores que revelan la situación demográfica del país, información de gran relevancia para la planificación nacional, regional y local en diversos campos. Uno de estos principales campos de acción es la salud pública, para la cual la tasa de mortalidad infantil se considera uno de los indicadores prioritarios dado que refleja no solo las condiciones de salud de la población infante, sino también los niveles de desarrollo del país, pues depende de la calidad de la atención de la salud, principalmente de la prenatal y perinatal, así como de las condiciones de saneamiento. Por tanto, su continuo monitoreo es fundamental para diseñar, implementar y evaluar políticas de salud pública orientadas a disminuir y erradicar aquellas que son prevenibles.

Para la serie de incentivos salariales del sector público, la función `auto.arima()` indica que el mejor modelo es un $ARIMA(0,0,1)(1,1,0)_{12}$, mientras que la sobreparametrización sugiere un $ARIMA(2,1,0)(1,2,0)_{12}$ como el más adecuado. Los resultados del cuadro \ref{tab:comparaciones_arima_mejores_reales} y la Figura \ref{fig:pronostico_INCENTIVOS} muestran que nuevamente los pronósticos obtenidos son superiores utilizando la sobreparametrización al analizar los pronósticos, y aunque no presenta las mejores medidas de ajuste, la diferencia con los otros modelos no es tan grande.

Por último, los modelos ajustados para pronosticar los intereses y comisiones del sector público son un $ARIMA(0,0,1)(0,1,0)_{12}$ para el caso de la función `auto.arima()` y un $ARIMA(0,1,2)(0,1,0)_{12}$. En este caso, la sobreparametrización es superior en dos de las tres medidas de rendimiento y en las medidas de bondad de ajuste, tal y como muestra el cuadro \ref{tab:comparaciones_arima_peores_reales}, mientras que la Figura \ref{fig:pronostico_INTERESES} muestra de manera gráfica los pronósticos obtenidos, que son bastante similares pues ambos modelos difieren solamente en un parámetro para la parte no estacional.

\subsection{Discusiones}

El uso de la sobreparametrización propuesto mediante un algoritmo de selección de modelos implementado en esta investigación permite evaluar una gama más amplia de modelos ARIMA al definir un máximo en la cantidad de parámetros para las partes estacionales y no estacionales de la series cronológicas, pues al definir este máximo se definen todos los posibles escenarios que posteriormente evalúan el aporte de cada nuevo término a los pronósticos. La incorporación de estos nuevos parámetros en los modelos ARIMA son validados mediante pruebas de significancia estadística, particiones de la serie cronológica, medidas de bondad de ajuste de los modelos y sus correspondientes medidas de rendimiento.

Como parte de la investigación, la series cronológicas utilizadas de forma simulada y generadas a partir de registros administrativos muestran como el uso de la sobreparametrización iguala y en muchos casos mejora la calidad de los pronósticos obtenidos en comparación a métodos ya establecidos, como es el caso de la función `auto.arima()`, o estimación de modelos más genéricos con un bajo número de parámetros, como los modelos estándar $ARIMA(1,1,1)$ o $ARIMA(1,1,1)(1,1,1)_{12}$. 

Al tener datos que vienen de un proceso con bajo número de parámetros los pronósticos obtenidos se terminan volviendo constantes en el caso de series no estacionales, sin embargo el uso de la sobreparametrización logra captar de buena manera el comportamiento de la serie en comparación a las otras alternativas más utilizadas y, además, cuando el proceso que gobierna la serie es de un mayor grado, la metodología propuesta, al considerar un mayor espectro paramétrico, es capaz de capturar de mejor forma el comportamiento de la serie y conseguir pronósticos con una precisión mayor al de los métodos más tradicionales. Lo anterior representa una mejora en cuanto a la utilización de modelos ARIMA para el pronóstico de series cronológicas, lo cual a su vez aporta herramientas para la toma de decisiones relacionadas a este tipo de análisis.

Además, en términos computacionales, ejecutar la sobreparametrización sobre equipos con 8Gb de memoria RAM o superiores no es algo que acortará el tiempo de estimación, pues simplemente es algo relacionado al almacenamiento de los objetos de R que se van creando. El uso de servicios gratuitos como Google Colab son una excelente alternativa para este tipo de procesos, pues tienen habilitado una capacidad más que aceptable de memoria y son capaces de ejecutar los procesos no solo mediante CPU's, sino también mediante GPU's, las cuales sí podrían reducir en cierta medida el tiempo de procesamiento.

Una potencial mejora al uso de la sobreparametrización es la inclusión semi-automática de regresores para controlar cambios estructurales de la serie cronológica en estudio, pues estos coeficientes adicionales podrían controlar cambios particulares en la serie y que podrían mejorar la precisión de los pronósticos.

Lo anterior también abre una futura ventana de investigación, y es la posibilidad de validar el uso de la sobreparametrización sobre las demás alternativas disponibles haciendo un mayor número de realizaciones para cada proceso simulado, esto con la finalidad de poder generalizar el comportamiento del método propuesto ante distintos escenarios que podrían presentarse para un mismo proceso $ARIMA(p,d,q)(P,D,Q)_s$.

La metodología aquí propuesta se encuentra disponible de manera abierta mediante el paquete de R `popstudy`, el cual fue desarrollado para esta investigación y cuenta con los procedimientos previamente descritos. Se encuentra disponible en un repositorio de Github[^8] y además en el repositorio CRAN[^9], que es la fuente oficial de los paquetes del lenguaje R.

[^8]: [https://github.com/cgamboasanabria/popstudy](https://github.com/cgamboasanabria/popstudy)
[^9]: [https://cran.r-project.org/web/packages/popstudy/index.html](https://cran.r-project.org/web/packages/popstudy/index.html).












```{r, eval=FALSE}
#En el campo demográfico, por ejemplo, las estadísticas vitales son sistematizadas y divulgadas año tras año, por tanto, revelan los cambios acontecidos durante este periodo. Esta información junto con la proveniente de los censos de población constituye la base para construir los diferentes índices, tasas y otros indicadores que revelan la situación demográfica del país, información de gran relevancia para la planificación nacional, regional y local en diversos campos. Uno de estos principales campos de acción es la salud pública, para la cual la tasa de mortalidad infantil se considera uno de los indicadores prioritarios dado que refleja no solo las condiciones de salud de la población infante, sino también los niveles de desarrollo del país, pues depende de la calidad de la atención de la salud, principalmente de la prenatal y perinatal, así como de las condiciones de saneamiento. Por tanto, su continuo monitoreo es fundamental para diseñar, implementar y evaluar políticas de salud pública orientadas a disminuir y erradicar aquellas que son prevenibles [@calidad_vitales].
```



